os: linux
language: shell

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

git:
  depth: false
  quiet: true

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - BUILD_NPROC=8
    - BUILD_PERLPROC=20
    - COMPOSE_ENV=test
    - COMPOSE_HTTP_TIMEOUT=120
    - COMPOSE_INTERACTIVE_NO_CLI=1
    - DOCKER_WEB_HOSTNAME=infocmdb.local
    - IMAGE_TAG=ci

before_install:
  - git fetch --all --tags
  - echo "install specific docker-compose Version '${DOCKER_COMPOSE_VERSION}'."
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker version
  - docker-compose version

jobs:
  fast_finish: true
  allow_failures:
    - env: COMPOSE_ENV_PHP_VERSION=7
  include:
    - stage: "testing"
      name: "PHP 7.3 Version"
      env: COMPOSE_ENV_PHP_VERSION=7.3
    - name: "PHP 7.1 Version"
      env: COMPOSE_ENV_PHP_VERSION=7.1
    - name: "PHP 7 latest Version"
      env: COMPOSE_ENV_PHP_VERSION=7

script:
  - set -e
  - ./run setup
  - ./run build
  - ./run up
  - ./run execute_tests unit --steps
  - ./run execute_tests api --steps
  - ./run execute_tests apiV2 --steps
  - ./run execute_tests functional --steps
  - ./run execute_tests acceptance --steps
  - docker-compose logs

after_script:
  - docker images

before_deploy:
  - set -e
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git describe --tags --long --always > version_info.txt
  - echo -n "Cmdb Version "
  - cat version_info.txt
  - ./run setup
  - ./run build

deploy:
  - provider: script
    cleanup: true
    on:
      tags: true
      branch: master
    env:
      - COMPOSE_ENV_PHP_VERSION=7.3
      - COMPOSE_ENV=prod
      - IMAGE_TAG=release
      - REGISTRY_TARGET=infonova
    script: ./deploy/publish_docker_images.sh ${IMAGE_TAG} ${REGISTRY_TARGET}
  - provider: script
    cleanup: true
    on:
      branch: develop
    env:
      - COMPOSE_ENV_PHP_VERSION=7.3
      - COMPOSE_ENV=prod
      - IMAGE_TAG=nightly
      - COMPOSE_DOCKER_REGISTRY=infonova
    script: docker-compose push

# vim:set et ts=2 sw=2:
