version: "3.4"

services:

  mariadb:
    tmpfs:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_TESTING}

  php:
    build:
      args:
        APPLICATION_ENV: testing
    volumes:
      - "./data/logs:/app/data/logs"
      - "./tests/_output:/app/tests/_output"
    environment:
      - APPLICATION_ENV=testing
      - DB_DATABASE=${DB_DATABASE_TESTING}
      - DB_DATABASE_TESTING=${DB_DATABASE_TESTING}
      - DB_SEEDING_ENABLED=0

  cron:
    environment:
      - APPLICATION_ENV=testing

  web:
    environment:
      - APPLICATION_ENV=testing
    ports:
      - "${DOCKER_WEB_PORT}:80"
      - "${DOCKER_WEB_SSL_PORT}:443"
    networks:
      default:
        aliases:
          - cmdb.test.local
          - ${DOCKER_WEB_HOSTNAME}

  hub:
    image: elgalu/selenium:${COMPOSE_ENV_SELENIUM_VERSION:-3}
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium:${COMPOSE_ENV_SELENIUM_VERSION:-3}
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=false
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=${DOCKER_SELENIUM_HUB_PORT}
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  mailcatcher:
    image: schickling/mailcatcher
