language: php

sudo: false

env:
  global:
    - COMPOSER_ARGS="" TMPDIR=/tmp USE_XDEBUG=false

branches:
  only:
    master

install:
  - phpenv rehash
  - travis_retry composer update --no-interaction --prefer-source $COMPOSER_ARGS

stages:
  - style check
  - phpstan analysis

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi

jobs:
  fast_finish: true
  include:
    - stage: style check
      php: 7.2
      env: TMPDIR=/tmp USE_XDEBUG=false
      script:
        - composer style-check
    - stage: phpstan analysis
      php: 7.2
      env: TMPDIR=/tmp USE_XDEBUG=false
      script:
        - composer phpstan
